---
  host:
    description: "Livestatus host address"
    type: "string"
    secret: false
    required: true
  port:
    description: "Livestatus listening port"
    type:  "integer"
    secret: false
    required: true
